export const ADD_GROCERY_LIST = "ADD_GROCERY_LIST";
export const REMOVE_GROCERY_LIST = "REMOVE_GROCERY_LIST";
export const REMOVE_ALL_LISTS = "REMOVE_ALL_LISTS";
export const ADD_GROCERY_ITEM = "ADD_GROCERY_ITEM";
export const REMOVE_GROCERY_ITEM = "REMOVE_GROCERY_ITEM";
